version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    steps:
      - checkout
      - run: lein test

#  publish:
#    docker:
#      - image: circleci/clojure:openjdk-11-lein
#    steps:
#      - checkout
#      - run: lein deploy clojars


workflows:
  version: 2
  build-publish:
    jobs:
      - build
#      - publish:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master