name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Start mongo
      run:  sudo docker run --rm -d -p 27017:27017 mongo
    - name: Run tests
      run: lein test
    - name: Publish
      run: lein deploy clojars
